version: "3.2"
services:
  db:
    image: marveldb:1.0 
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12Marvel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12Marvel
      - MYSQL_DATABASE=marvelDB
    networks:
      - db
    command: --default-authentication-plugin=mysql_native_password
  web:
    image: cnc-nginx:1.1
    environment:
      - MYSQL_ROOT_PASSWORD=12Marvel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12Marvel
      - MYSQL_DATABASE=marvelDB
      - MYSQL_HOST=db
    ports:
      - "8080:80"
    networks:
      - external-net
      - db
    depends_on:
      - db
    volumes:
      - ./src:/app/public

networks:
  external-net:
    external:
      name: external-net
  db:
    driver: bridge