version: "3.2"
services:
  cnc-db:
    image: cnc-pg:${Version}
    restart: always
    environment:
      -  POSTGRES_DATABASE=machines
    ports:
      - "5432:5432"
    networks:
      - cncnetwork
    volumes:
      - dbdata:/var/lib/mysql
  cnc-api:
    image: cnc-node-api:${Version}
    restart: always
    environment:
      - POSTGRES_DATABASE=machines
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12Marvel
    ports:
      - "3000:3000"
    depends_on:
      - cnc-db
    networks:
      - cncnetwork
    volumes:
      - dbdata:/var/lib/api
  cnc-web:
    image: cnc-web:${Version}
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - cnc-db
    networks:
      - cncnetwork
    volumes:
      - dbdata:/var/lib/web
volumes:
  dbdata:
networks:
  cncnetwork: