version: "3.2"
services:
  cnc-webgui-db:
    image: cnc-mysql:1.0 
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12Marvel
      - MYSQL_DATABASE=machines
      - MYSQL_ROOT_HOST=%
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src:/cnc-webgui/db
  web:
    image: cnc-web:1.0
    environment:
      - MYSQL_ROOT_PASSWORD=12Marvel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12Marvel
      - MYSQL_DATABASE=machines
      - MYSQL_HOST=db
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - cnc-webgui-db
    volumes:
      - ./src:/cnc-webgui/web