version: "3.2"
services:
  cnc-webgui-db:
    image: 192.168.1.140:5000/cnc-webgui-db:1.1 
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12Marvel
      - MYSQL_DATABASE=machines
      - MYSQL_ROOT_HOST="%"
  web:
    image: 192.168.1.140:5000/cnc-php-nginx:1.2
    environment:
      - MYSQL_ROOT_PASSWORD=12Marvel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12Marvel
      - MYSQL_DATABASE=machines
      - MYSQL_HOST=db
    ports:
      - "8080:80"
    depends_on:
      - cnc-webgui-db
    volumes:
      - ./src:/app/public