version: "3.2"
services:
  cnc-webgui-db:
    image: cnc-mysql:1.2
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12Marvel
      - MYSQL_DATABASE=machines
      - MYSQL_ROOT_HOST=%
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - cncnetwork
    volumes:
      - dbdata:/var/lib/mysql
  web:
    image: cnc-web:1.2
    environment:
      - MYSQL_ROOT_PASSWORD=12Marvel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12Marvel
      - MYSQL_DATABASE=machines
      - MYSQL_HOST=db
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - cnc-webgui-db
    networks:
      - cncnetwork
    volumes:
      - dbdata:/var/lib/web
volumes:
  dbdata:
networks:
  cncnetwork: 