name: Docker Image CI

on:
  push:
    branches: 
    - Dev
    - master
  pull_request:
    branches: [ "Dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd CnC-WebGUI/MySQL-Docker/
        docker build . -t cnc-webgui-mysql -f Dockerfile

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd CnC-WebGUI/Nginx-Docker/
        docker build . -t cnc-webgui-nginx -f Dockerfile
