name: Docker Image CI

on:
  push:
    branches: 
    - Dev
    - master
  pull_request:
    branches: [ "Dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file /CnC-WebGUI/MySQL-Docker/Dockerfile --tag my-image-name:$(date +%s)
