name: Docker Image Build Test

on:
  push:
    branches: 
    - Dev
    - master
  pull_request:
    branches: [ "Dev" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd CnC-WebGUI/Postgress-Docker/
        docker build . -t cnc-webgui-pg -f Dockerfile

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd CnC-WebGUI/Nginx-Docker/
        docker build . -t cnc-webgui-nginx -f Dockerfile

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd CnC-WebGUI/Nodejs-Docker/
        docker build . -t cnc-webgui-api -f Dockerfile

    - name: Send Notification ntfy
      run: |
        curl \
        -H "Title: CnC-WebGUI Successfully Built" \
        -H "Priority: default" \
        -H "Tags: warning,skull" \
        -d "The Github action has been successfull." \
      https://notify.rp-helpdesk.com/Github
